name: Cigarettes
version: '1.0'
main: com.anuraaaan.cigarettes.Cigarettes
api-version: '1.21.5'
authors: [anuraaaan]
commands:
  cigarettes:
    description: Plugin command
    aliases:
      - cig

softdepend:
  - ItemsAdder

permissions:
  cigarettes.reload:
    description: Restart the configuration
    default: op
  cigarettes.add:
    description: Add nicotine
    default: op
  cigarettes.give:
    description: Give out an item
    default: op
